import type { Metadata } from "next";
import {Odibee_Sans,Port_Lligat_Sans} from "next/font/google"
import "./globals.css";

const odibee_sans = Odibee_Sans({
  subsets: ['latin'],
  weight: ['400'],
  variable: "--font-odibee"
})

const port_lligat_sans = Port_Lligat_Sans({
  subsets: ['latin'],
  weight: ["400"],
  variable: "--font-port"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${odibee_sans.variable} ${port_lligat_sans.variable} font-odibee`}
      >
        {children}
      </body>
    </html>
  );
}
